//! `pgbr-ffi` is the C ABI surface consumed by the legacy C build during the C->Rust migration.
//!
//! Each phase moves an additional `extern "C"` shim into this crate. The header `pgbr_ffi.h` is
//! regenerated by cbindgen from this crate at build time.

use core::ffi::{CStr, c_char};

/// Version string of the embedded Rust FFI shim, tracking `Cargo.toml`'s workspace version.
///
/// Baked into the static archive and returned to C as a NUL-terminated UTF-8 string.
// SAFETY: `CARGO_PKG_VERSION` is provided by Cargo and is guaranteed not to contain interior
// NULs; appending a single `\0` produces a well-formed C string.
const PGBR_FFI_VERSION: &CStr =
    unsafe { CStr::from_bytes_with_nul_unchecked(concat!(env!("CARGO_PKG_VERSION"), "\0").as_bytes()) };

/// Returns a pointer to a static, NUL-terminated UTF-8 string identifying the Rust FFI shim
/// version. The pointer is valid for the lifetime of the process and must not be freed.
#[unsafe(no_mangle)]
pub const extern "C" fn pgbr_version() -> *const c_char {
    PGBR_FFI_VERSION.as_ptr()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_is_non_empty_and_matches_cargo() {
        let ptr = pgbr_version();
        assert!(!ptr.is_null());
        // SAFETY: pgbr_version() returns a pointer to PGBR_FFI_VERSION, a 'static CStr.
        let cstr = unsafe { CStr::from_ptr(ptr) };
        let rust_str = cstr.to_str().expect("ffi version is utf-8");
        assert_eq!(rust_str, env!("CARGO_PKG_VERSION"));
        assert!(!rust_str.is_empty());
    }
}
