//! `pgbr-ffi` is the C ABI surface consumed by the legacy C build during the C->Rust migration.
//!
//! Each phase moves an additional `extern "C"` shim into this crate. The header `pgbr_ffi.h` is
//! regenerated by cbindgen from this crate at build time.
//!
//! Every C-callable function defined here goes through the [`with_panic_guard`] helper so panics
//! crossing the FFI boundary are caught and translated into a typed [`pgbr_error::ErrorType`]
//! value rather than aborting the process. C callers always observe well-defined return values
//! and can read the panic message via [`pgbr_last_error_msg`].

use core::ffi::{CStr, c_char};
use std::ffi::CString;
use std::sync::atomic::{AtomicPtr, Ordering};

use pgbr_encode::{self as encode, EncodingType};
use pgbr_error::{Error, ErrorType, clear_last_error, last_error_code, last_error_message, set_last_error};

/// Version string of the embedded Rust FFI shim, tracking `Cargo.toml`'s workspace version.
///
/// Baked into the static archive and returned to C as a NUL-terminated UTF-8 string.
// SAFETY: `CARGO_PKG_VERSION` is provided by Cargo and is guaranteed not to contain interior
// NULs; appending a single `\0` produces a well-formed C string.
const PGBR_FFI_VERSION: &CStr = unsafe { CStr::from_bytes_with_nul_unchecked(concat!(env!("CARGO_PKG_VERSION"), "\0").as_bytes()) };

/// Default value an `extern "C"` shim returns after a panic crosses its boundary.
///
/// Implemented for every type used as a return value from a [`with_panic_guard`]-wrapped FFI
/// values are deliberately chosen so a C caller observing them and inspecting
/// [`pgbr_last_error_code`] can distinguish a panic (`Unknown` = 125) from a clean operation.
pub trait FfiPanicReturn {
    /// Sentinel value returned when the wrapped Rust code panics.
    fn ffi_panic_return() -> Self;
}

impl FfiPanicReturn for () {
    fn ffi_panic_return() {}
}

impl FfiPanicReturn for i32 {
    fn ffi_panic_return() -> Self {
        -1
    }
}

impl FfiPanicReturn for usize {
    fn ffi_panic_return() -> Self {
        Self::MAX
    }
}

impl FfiPanicReturn for u32 {
    fn ffi_panic_return() -> Self {
        0
    }
}

impl FfiPanicReturn for u64 {
    fn ffi_panic_return() -> Self {
        0
    }
}

impl FfiPanicReturn for isize {
    fn ffi_panic_return() -> Self {
        -1
    }
}

impl<T> FfiPanicReturn for *const T {
    fn ffi_panic_return() -> Self {
        core::ptr::null()
    }
}

impl<T> FfiPanicReturn for *mut T {
    fn ffi_panic_return() -> Self {
        core::ptr::null_mut()
    }
}

/// Run `body` while protecting the FFI boundary from a Rust panic.
///
/// If the body panics, the panic is recorded as the thread's last error
/// (category [`pgbr_error::ErrorType::Unknown`]) and the function returns the type's
/// [`FfiPanicReturn`] sentinel. Without this guard, a panic crossing the FFI boundary is
/// undefined behaviour.
///
/// The guard does **not** clear the thread-local error slot. Reader-style shims like
/// `pgbr_last_error_code` would otherwise erase the very value the C caller is trying to read.
/// A fallible Rust shim that wants to start from a clean slate should call
/// [`pgbr_error::clear_last_error`] inside the body before doing work.
fn with_panic_guard<R, F>(body: F) -> R
where
    R: FfiPanicReturn,
    F: FnOnce() -> R,
{
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(body)).unwrap_or_else(|_| {
        record_panic_as_last_error();
        R::ffi_panic_return()
    })
}

/// Internal helper used by [`with_panic_guard`] when `catch_unwind` traps a panic. Records a
/// typed `Unknown` error so the C caller can read the panic via [`pgbr_last_error_msg`].
fn record_panic_as_last_error() {
    set_last_error(Error::new(ErrorType::Unknown, "rust panic crossed FFI boundary"));
}

/// Returns a pointer to a static, NUL-terminated UTF-8 string identifying the Rust FFI shim
/// version. The pointer is valid for the lifetime of the process and must not be freed.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_version() -> *const c_char {
    with_panic_guard(|| PGBR_FFI_VERSION.as_ptr())
}

/// Numeric code of the calling thread's last error, or `0` if no error is set.
///
/// Mirrors the C `errorTypeCode` numbering. Reads the same thread-local slot populated by Rust
/// shims via `pgbr_error::set_last_error` and by the C-side helpers below.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_code() -> i32 {
    with_panic_guard(last_error_code)
}

/// Pointer to a NUL-terminated UTF-8 message of the calling thread's last error, or `null` if no
/// error is set.
///
/// The returned pointer is valid until the next call into `pgbr_last_error_*` on the same thread
/// (any of `pgbr_last_error_set`, `pgbr_last_error_clear`, `pgbr_last_error_take_code`). The
/// caller must not free it.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_msg() -> *const c_char {
    with_panic_guard(last_error_message)
}

/// Sets the calling thread's last error to the given typed `code` and `message_utf8` C string.
///
/// Returns `0` on success, `-1` if `code` is not part of the shared error table or
/// `message_utf8` is null or not valid UTF-8. On `-1`, the existing thread-local error is left
/// untouched.
///
/// # Safety
///
/// `message_utf8` must point to a NUL-terminated, valid UTF-8 byte sequence readable for the
/// duration of the call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_last_error_set(code: i32, message_utf8: *const c_char) -> i32 {
    with_panic_guard(|| {
        let Some(error_type) = ErrorType::from_code(code) else {
            return -1;
        };
        if message_utf8.is_null() {
            return -1;
        }
        // SAFETY: caller guarantees `message_utf8` is NUL-terminated and readable.
        let cstr = unsafe { CStr::from_ptr(message_utf8) };
        let Ok(message) = cstr.to_str() else {
            return -1;
        };
        set_last_error(Error::new(error_type, message));
        0
    })
}

/// Removes the calling thread's last error and returns its numeric code.
///
/// Returns `0` if no error was set. The associated message becomes invalid as soon as this
/// function returns.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_take_code() -> i32 {
    with_panic_guard(|| pgbr_error::take_last_error().map_or(0, |e| e.code()))
}

/// Clears the calling thread's last error.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_clear() {
    with_panic_guard(clear_last_error);
}

/// Logging callback registered by the C side to receive every Rust-originated log line.
///
/// The first argument is a numeric log level matching the C `LogLevel` enum (off=0, assert=1,
/// error=2, protocol=3, warn=4, info=5, detail=6, debug=7, trace=8). The second argument is a
/// pointer to a NUL-terminated UTF-8 message valid only during the call.
pub type PgbrLogCallback = unsafe extern "C" fn(level: i32, message_utf8: *const c_char);

static LOG_CALLBACK_RAW: AtomicPtr<()> = AtomicPtr::new(core::ptr::null_mut());

/// Registers a callback the Rust side invokes for every log line.
///
/// The callback is stored atomically and may be invoked from any thread. Replacing it is atomic
/// with respect to in-flight calls; in-flight calls always observe either the previous or the new
/// pointer, never a torn value. To stop receiving callbacks, use [`pgbr_log_clear_callback`].
///
/// # Safety
///
/// `callback` must be a valid `extern "C"` function pointer that remains live for as long as it
/// can be reached by the Rust side. The C side guarantees this by pointing to a static function.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_log_set_callback(callback: PgbrLogCallback) {
    with_panic_guard(|| {
        let raw: *mut () = callback as *mut ();
        LOG_CALLBACK_RAW.store(raw, Ordering::SeqCst);
    });
}

/// Removes any logging callback previously registered through [`pgbr_log_set_callback`]. After
/// this call, [`pgbr_log`] is a no-op until a new callback is installed.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_log_clear_callback() {
    with_panic_guard(|| {
        LOG_CALLBACK_RAW.store(core::ptr::null_mut(), Ordering::SeqCst);
    });
}

/// Forwards a log message to the registered callback, if any. Drops the message silently if no
/// callback has been set or if the message contains an interior NUL that cannot be removed.
///
/// Internal API used by other workspace crates; not exposed through cbindgen because it accepts
/// Rust types.
pub fn pgbr_log(level: i32, message: &str) {
    let raw = LOG_CALLBACK_RAW.load(Ordering::SeqCst);
    if raw.is_null() {
        return;
    }
    // SAFETY: the only writer of LOG_CALLBACK_RAW is `pgbr_log_set_callback`, which stores either
    // null or a `PgbrLogCallback` cast to `*mut ()`. We've checked for null above, so the pointer
    // is a valid function pointer when the callback was registered. Replacement is atomic.
    let callback: PgbrLogCallback = unsafe { core::mem::transmute(raw) };

    let cleaned: Vec<u8> = message.bytes().filter(|b| *b != 0).collect();
    let Ok(cstring) = CString::new(cleaned) else {
        return;
    };
    // SAFETY: the registered callback abides by extern "C" calling conventions and accepts a
    // pointer to a NUL-terminated UTF-8 buffer valid for the duration of the call.
    unsafe { callback(level, cstring.as_ptr()) };
}

/// Numeric mapping of the C `LogLevel` enum used by [`pgbr_log`] and [`PgbrLogCallback`]. The
/// values match the C side so a Rust producer and a C consumer can share a single integer.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LogLevel {
    /// Logging disabled.
    Off = 0,
    /// Programmer assertion violation; treated as fatal by the C side.
    Assert = 1,
    /// Recoverable error.
    Error = 2,
    /// Protocol-level diagnostic.
    Protocol = 3,
    /// Warning.
    Warn = 4,
    /// Informational message.
    Info = 5,
    /// Detailed informational message.
    Detail = 6,
    /// Debug-level diagnostic.
    Debug = 7,
    /// Trace-level diagnostic.
    Trace = 8,
}

// ---------- pgbr-crypto xxhash bridge (Phase 8) ----------

use pgbr_crypto::xxhash3 as crypto_xxhash3;

/// Allocate a new XXH3-128 streaming state on the Rust heap and return an opaque pointer to it.
///
/// The returned pointer must eventually be passed to [`pgbr_xxhash3_state_free`]; otherwise the
/// state leaks. Returns null on allocation failure (only if the OOM hook panics, in which case
/// the panic is caught and translated to `ErrorType::Unknown`).
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_xxhash3_state_new() -> *mut core::ffi::c_void {
    with_panic_guard(|| {
        let boxed: Box<crypto_xxhash3::State> = Box::new(crypto_xxhash3::State::new());
        Box::into_raw(boxed).cast::<core::ffi::c_void>()
    })
}

/// Drop the streaming state allocated by [`pgbr_xxhash3_state_new`]. No-op on null.
///
/// # Safety
///
/// `state` must be a pointer previously returned by [`pgbr_xxhash3_state_new`] that has not yet
/// been freed.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_xxhash3_state_free(state: *mut core::ffi::c_void) {
    with_panic_guard(|| {
        if state.is_null() {
            return;
        }
        // SAFETY: caller upholds the ownership invariant — the pointer came from
        // `pgbr_xxhash3_state_new` and has not been freed. Dropping the Box runs the
        // xxhash-rust state destructor.
        let _ = unsafe { Box::from_raw(state.cast::<crypto_xxhash3::State>()) };
    });
}

/// Feed `size` bytes from `data` into the streaming state.
///
/// Returns 0 on success, -1 if `state` is null. On -1 the thread-local last error is set.
///
/// # Safety
///
/// - `state` must be a non-null pointer from [`pgbr_xxhash3_state_new`].
/// - `data` must point to at least `size` readable bytes (or be null when `size == 0`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_xxhash3_state_update(state: *mut core::ffi::c_void, data: *const u8, size: usize) -> i32 {
    with_panic_guard(|| {
        if state.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_xxhash3_state_update: state is null"));
            return -1;
        }
        // SAFETY: caller guarantees the state pointer is valid and unique.
        let state = unsafe { &mut *state.cast::<crypto_xxhash3::State>() };
        let slice: &[u8] = if size == 0 {
            &[]
        } else if data.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_xxhash3_state_update: data is null"));
            return -1;
        } else {
            // SAFETY: caller guarantees `data` is readable for `size` bytes.
            unsafe { core::slice::from_raw_parts(data, size) }
        };
        state.update(slice);
        0
    })
}

/// Finalize the hash and write up to `dst_size` canonical bytes (high 64 first, low 64 next,
/// big-endian) to `dst`. `dst_size` must be in `1..=16`.
///
/// Returns 0 on success, -1 on invalid arguments. On -1 the thread-local last error is set.
///
/// # Safety
///
/// - `state` must be a non-null pointer from [`pgbr_xxhash3_state_new`].
/// - `dst` must point to at least `dst_size` writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_xxhash3_state_digest(state: *const core::ffi::c_void, dst: *mut u8, dst_size: usize) -> i32 {
    with_panic_guard(|| {
        if state.is_null() || dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_xxhash3_state_digest: null pointer"));
            return -1;
        }
        if !(1..=crypto_xxhash3::HASH_SIZE_MAX).contains(&dst_size) {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_xxhash3_state_digest: dst_size {dst_size} out of range 1..=16"),
            ));
            return -1;
        }
        // SAFETY: caller guarantees the state pointer is valid.
        let state = unsafe { &*state.cast::<crypto_xxhash3::State>() };
        // SAFETY: caller guarantees `dst` is writable for `dst_size` bytes.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst, dst_size) };
        state.digest_into(dst_slice);
        0
    })
}

/// Single-shot XXH3-128 hash. Writes up to `dst_size` canonical bytes (`1..=16`) into `dst`.
///
/// # Safety
///
/// - `data` must point to at least `data_size` readable bytes (or be null when `data_size==0`).
/// - `dst` must point to at least `dst_size` writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_xxhash3_one(data: *const u8, data_size: usize, dst: *mut u8, dst_size: usize) -> i32 {
    with_panic_guard(|| {
        if dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_xxhash3_one: dst is null"));
            return -1;
        }
        if !(1..=crypto_xxhash3::HASH_SIZE_MAX).contains(&dst_size) {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_xxhash3_one: dst_size {dst_size} out of range 1..=16"),
            ));
            return -1;
        }
        let data_slice: &[u8] = if data_size == 0 {
            &[]
        } else if data.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_xxhash3_one: data is null"));
            return -1;
        } else {
            // SAFETY: caller guarantees `data` is readable for `data_size` bytes.
            unsafe { core::slice::from_raw_parts(data, data_size) }
        };
        // SAFETY: caller guarantees `dst` is writable for `dst_size` bytes.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst, dst_size) };
        crypto_xxhash3::one_128(data_slice, dst_slice);
        0
    })
}

// ---------- pgbr-postgres bridge (Phase 7) ----------

/// CRC-32C (Castagnoli) checksum of `size` bytes at `data`. Mirrors the legacy `crc32cOne`.
///
/// # Safety
///
/// `data` must point to at least `size` readable bytes (or be null when `size == 0`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crc32c_one(data: *const u8, size: usize) -> u32 {
    with_panic_guard(|| {
        if size == 0 {
            return pgbr_postgres::crc32c_one(&[]);
        }
        if data.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crc32c_one: data is null"));
            return 0;
        }
        // SAFETY: caller upholds the read-of-size precondition above.
        let slice = unsafe { core::slice::from_raw_parts(data, size) };
        pgbr_postgres::crc32c_one(slice)
    })
}

// ---------- pgbr-encode bridge (Phase 6) ----------

/// Format a [`pgbr_encode::DecodeError`] using the legacy C error wording (`base64 size ...`,
/// `hex invalid character ...`) so the C wrappers in `src/common/encode.c` continue to throw
/// `FormatError` messages that match the existing test expectations.
fn format_decode_error(encoding: EncodingType, err: encode::DecodeError) -> String {
    let prefix = match encoding {
        EncodingType::Base64 | EncodingType::Base64Url => "base64",
        EncodingType::Hex => "hex",
    };
    match err {
        encode::DecodeError::InvalidLength { len, group } => {
            format!("{prefix} size {len} is not evenly divisible by {group}")
        }
        encode::DecodeError::InvalidCharacter { position } => {
            format!("{prefix} invalid character found at position {position}")
        }
        encode::DecodeError::PaddingMisplaced => {
            format!("{prefix} '=' character may only appear in last two positions")
        }
        encode::DecodeError::PaddingTrailing => {
            format!("{prefix} last character must be '=' if second to last is")
        }
        encode::DecodeError::Unsupported => format!("{prefix} decoding is not supported"),
    }
}

fn record_decode_error(encoding: EncodingType, err: encode::DecodeError) {
    set_last_error(Error::new(ErrorType::Format, format_decode_error(encoding, err)));
}

/// Encode `src_size` bytes at `src` into `dst` using the encoding selected by `encoding_code`
/// (0=Base64, 1=Base64Url, 2=Hex). Mirrors the legacy `encodeToStr` from `src/common/encode.h`.
///
/// The function writes `pgbr_encode::encoded_len(encoding, src_size) + 1` bytes (the encoded
/// form plus a trailing NUL).
///
/// # Safety
///
/// - `src` must point to at least `src_size` readable bytes (or be null when `src_size == 0`).
/// - `dst` must point to a writable buffer of at least `encoded_len(encoding, src_size) + 1`
///   bytes.
/// - `encoding_code` must be one of 0, 1, 2; any other value sets the thread-local error and
///   leaves `dst` untouched.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_encode_to_str(encoding_code: i32, src: *const u8, src_size: usize, dst: *mut c_char) {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return;
        };
        if dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_encode_to_str: dst is null"));
            return;
        }

        let dst_len = encode::encoded_len(encoding, src_size) + 1;
        // SAFETY: caller upholds the buffer size + non-null preconditions.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst.cast::<u8>(), dst_len) };
        let src_slice: &[u8] = if src_size == 0 {
            &[]
        } else {
            // SAFETY: caller guarantees `src` is readable for `src_size` bytes.
            unsafe { core::slice::from_raw_parts(src, src_size) }
        };

        encode::encode(encoding, src_slice, dst_slice);
    });
}

/// Returns `pgbr_encode::encoded_len(encoding, src_size)` — the size of the encoded form
/// excluding the trailing NUL. Mirrors the legacy `encodeToStrSize`.
///
/// Returns `usize::MAX` if `encoding_code` is unknown; the C wrapper translates that into a
/// `FormatError` throw via the thread-local last-error slot.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_encode_to_str_size(encoding_code: i32, src_size: usize) -> usize {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return usize::MAX;
        };
        encode::encoded_len(encoding, src_size)
    })
}

/// Decode the NUL-terminated UTF-8 string at `src` into `dst` using the encoding selected by
/// `encoding_code`. Mirrors the legacy `decodeToBin`.
///
/// Returns `0` on success, `-1` if validation failed; on `-1`, the thread-local last error is
/// populated with a `FormatError`-formatted message that the C wrapper re-throws.
///
/// # Safety
///
/// - `src` must be a valid NUL-terminated C string.
/// - `dst` must point to a writable buffer of at least `pgbr_decode_to_bin_size(encoding, src)`
///   bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_decode_to_bin(encoding_code: i32, src: *const c_char, dst: *mut u8) -> i32 {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return -1;
        };
        if src.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_decode_to_bin: src is null"));
            return -1;
        }

        // SAFETY: caller guarantees `src` is NUL-terminated.
        let cstr = unsafe { CStr::from_ptr(src) };
        let Ok(text) = cstr.to_str() else {
            set_last_error(Error::new(ErrorType::Format, "decode source is not valid utf-8"));
            return -1;
        };

        let needed = match encode::decoded_len(encoding, text) {
            Ok(n) => n,
            Err(err) => {
                record_decode_error(encoding, err);
                return -1;
            }
        };

        if needed > 0 && dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_decode_to_bin: dst is null"));
            return -1;
        }

        // SAFETY: caller upholds the dst sizing precondition.
        let dst_slice = if needed == 0 {
            &mut [][..]
        } else {
            unsafe { core::slice::from_raw_parts_mut(dst, needed) }
        };

        match encode::decode(encoding, text, dst_slice) {
            Ok(()) => 0,
            Err(err) => {
                record_decode_error(encoding, err);
                -1
            }
        }
    })
}

/// Computes the decoded byte size for the NUL-terminated string at `src`. Writes the result
/// through `out_size` and returns `0` on success, `-1` on validation failure.
///
/// On `-1`, `out_size` is left untouched and the thread-local last error carries the
/// `FormatError`-formatted reason.
///
/// # Safety
///
/// - `src` must be a valid NUL-terminated C string.
/// - `out_size` must point to a writable `usize` (8 bytes on 64-bit).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_decode_to_bin_size(encoding_code: i32, src: *const c_char, out_size: *mut usize) -> i32 {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return -1;
        };
        if src.is_null() || out_size.is_null() {
            set_last_error(Error::new(
                ErrorType::Assert,
                "pgbr_decode_to_bin_size: src or out_size is null",
            ));
            return -1;
        }

        // SAFETY: caller guarantees `src` is NUL-terminated.
        let cstr = unsafe { CStr::from_ptr(src) };
        let Ok(text) = cstr.to_str() else {
            set_last_error(Error::new(ErrorType::Format, "decode source is not valid utf-8"));
            return -1;
        };

        match encode::decoded_len(encoding, text) {
            Ok(n) => {
                // SAFETY: caller guarantees `out_size` is writable.
                unsafe { out_size.write(n) };
                0
            }
            Err(err) => {
                record_decode_error(encoding, err);
                -1
            }
        }
    })
}

// ---------- pgbr-crypto common bridge (Phase 10) ----------

/// Initialize OpenSSL once for the process (idempotent).
///
/// Mirrors the legacy `cryptoInit` body — combines `openssl::init` with
/// `OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL)` so per-platform OpenSSL config files keep
/// applying.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_crypto_init() {
    with_panic_guard(pgbr_crypto::common::init);
}

/// Drain one error from the calling thread's OpenSSL queue and return its code, or `0`.
///
/// Direct equivalent of `ERR_get_error()` — used by `cryptoError` to feed `cryptoErrorCode`.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_crypto_last_error_get() -> u64 {
    with_panic_guard(pgbr_crypto::common::last_error_get)
}

/// Write the OpenSSL reason string for `code` (or "no details available") into `buf`.
///
/// Always NUL-terminates `buf` provided `buf_size >= 1`. Truncates silently when the reason is
/// longer than `buf_size - 1`. No-op when `buf` is null or `buf_size` is `0`.
///
/// # Safety
///
/// `buf` must point to a writable buffer of at least `buf_size` bytes (or be null when
/// `buf_size == 0`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_error_reason_into(code: u64, buf: *mut c_char, buf_size: usize) {
    with_panic_guard(|| {
        if buf.is_null() || buf_size == 0 {
            return;
        }
        // SAFETY: caller upholds the buffer-size contract above.
        let dst = unsafe { core::slice::from_raw_parts_mut(buf.cast::<u8>(), buf_size) };
        pgbr_crypto::common::error_reason_into(code, dst);
    });
}

/// Fill `buf` with `size` cryptographically strong random bytes via `RAND_bytes`.
///
/// No-op when `size == 0`. Mirrors the legacy `cryptoRandomBytes` (which itself ignored the
/// `RAND_bytes` return value).
///
/// # Safety
///
/// `buf` must point to a writable buffer of at least `size` bytes (or be null when `size == 0`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_random_bytes(buf: *mut u8, size: usize) {
    with_panic_guard(|| {
        if size == 0 {
            return;
        }
        if buf.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_random_bytes: buf is null"));
            return;
        }
        // SAFETY: caller upholds the buffer-size + non-null contract above.
        let dst = unsafe { core::slice::from_raw_parts_mut(buf, size) };
        let _ = pgbr_crypto::common::random_bytes(dst);
    });
}

// ---------- pgbr-crypto cipher bridge (Phase 12) ----------

/// Cipher block size in bytes for `cipher_code`, or `0` for unknown codes.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_crypto_cipher_block_size(cipher_code: i32) -> usize {
    with_panic_guard(|| pgbr_crypto::cipher::CipherType::from_code(cipher_code).map_or(0, pgbr_crypto::cipher::CipherType::block_size))
}

/// Required key size in bytes for `cipher_code`, or `0` for unknown codes.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_crypto_cipher_key_len(cipher_code: i32) -> usize {
    with_panic_guard(|| pgbr_crypto::cipher::CipherType::from_code(cipher_code).map_or(0, pgbr_crypto::cipher::CipherType::key_len))
}

/// Required IV size in bytes for `cipher_code`, or `0` for unknown codes.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_crypto_cipher_iv_len(cipher_code: i32) -> usize {
    with_panic_guard(|| pgbr_crypto::cipher::CipherType::from_code(cipher_code).map_or(0, pgbr_crypto::cipher::CipherType::iv_len))
}

/// Derive key + IV from `pass` and `salt` using `EVP_BytesToKey` (count = 1).
///
/// Writes the key into `key_out` and the IV into `iv_out`. `key_out_size` / `iv_out_size`
/// must be at least the cipher's required key / IV size — call
/// [`pgbr_crypto_cipher_key_len`] and [`pgbr_crypto_cipher_iv_len`] to size the buffers.
///
/// Returns `0` on success, `-1` on error (thread-local last error set).
///
/// # Safety
///
/// All pointers must be non-null and point to buffers of the documented sizes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_cipher_derive_key_iv(
    cipher_code: i32,
    digest_code: i32,
    salt: *const u8,
    salt_size: usize,
    pass: *const u8,
    pass_size: usize,
    key_out: *mut u8,
    key_out_size: usize,
    iv_out: *mut u8,
    iv_out_size: usize,
) -> i32 {
    with_panic_guard(|| {
        let Some(cipher) = pgbr_crypto::cipher::CipherType::from_code(cipher_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_crypto_cipher_derive_key_iv: unknown cipher code {cipher_code}"),
            ));
            return -1;
        };
        let Some(digest) = pgbr_crypto::hash::HashType::from_code(digest_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_crypto_cipher_derive_key_iv: unknown digest code {digest_code}"),
            ));
            return -1;
        };
        if salt.is_null() || pass.is_null() || key_out.is_null() || iv_out.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_cipher_derive_key_iv: null pointer"));
            return -1;
        }
        // SAFETY: caller upholds the size + non-null contracts above.
        let salt_slice = unsafe { core::slice::from_raw_parts(salt, salt_size) };
        // SAFETY: same.
        let pass_slice = unsafe { core::slice::from_raw_parts(pass, pass_size) };
        // SAFETY: same.
        let key_slice = unsafe { core::slice::from_raw_parts_mut(key_out, key_out_size) };
        // SAFETY: same.
        let iv_slice = unsafe { core::slice::from_raw_parts_mut(iv_out, iv_out_size) };
        match pgbr_crypto::cipher::derive_key_iv(cipher, digest, salt_slice, pass_slice, key_slice, iv_slice) {
            Ok(_) => 0,
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                -1
            }
        }
    })
}

/// Allocate a streaming cipher state with the given algorithm, mode, key and IV.
///
/// Returns null on error; inspect the thread-local last error for the cause.
///
/// # Safety
///
/// `key` / `iv` must point to readable buffers of the documented sizes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_cipher_state_new(
    cipher_code: i32,
    mode_code: i32,
    key: *const u8,
    key_size: usize,
    iv: *const u8,
    iv_size: usize,
) -> *mut core::ffi::c_void {
    with_panic_guard(|| {
        let Some(cipher) = pgbr_crypto::cipher::CipherType::from_code(cipher_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_crypto_cipher_state_new: unknown cipher code {cipher_code}"),
            ));
            return core::ptr::null_mut();
        };
        let Some(mode) = pgbr_crypto::cipher::Mode::from_code(mode_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_crypto_cipher_state_new: unknown mode code {mode_code}"),
            ));
            return core::ptr::null_mut();
        };
        if key.is_null() || iv.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_cipher_state_new: null pointer"));
            return core::ptr::null_mut();
        }
        // SAFETY: caller upholds the size + non-null contracts.
        let key_slice = unsafe { core::slice::from_raw_parts(key, key_size) };
        // SAFETY: same.
        let iv_slice = unsafe { core::slice::from_raw_parts(iv, iv_size) };
        match pgbr_crypto::cipher::State::new(cipher, mode, key_slice, iv_slice) {
            Ok(state) => Box::into_raw(Box::new(state)).cast::<core::ffi::c_void>(),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                core::ptr::null_mut()
            }
        }
    })
}

/// Drop a cipher state. No-op on null.
///
/// # Safety
///
/// `state` must be a pointer previously returned by [`pgbr_crypto_cipher_state_new`] that
/// has not yet been freed, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_cipher_state_free(state: *mut core::ffi::c_void) {
    with_panic_guard(|| {
        if state.is_null() {
            return;
        }
        // SAFETY: caller upholds the unique-ownership invariant.
        let _ = unsafe { Box::from_raw(state.cast::<pgbr_crypto::cipher::State>()) };
    });
}

/// Stream `src_size` bytes from `src` through the cipher state, writing up to `dst_size`
/// bytes to `dst`. Returns the number of bytes written (`>= 0`) on success or `-1` on error.
///
/// `dst` must have at least `src_size + cipher.block_size()` bytes of capacity.
///
/// # Safety
///
/// All pointers must be non-null and point to buffers of the documented sizes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_cipher_state_update(
    state: *mut core::ffi::c_void,
    src: *const u8,
    src_size: usize,
    dst: *mut u8,
    dst_size: usize,
) -> isize {
    with_panic_guard(|| {
        if state.is_null() || dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_cipher_state_update: null pointer"));
            return -1;
        }
        // SAFETY: caller guarantees the state pointer is alive.
        let state = unsafe { &mut *state.cast::<pgbr_crypto::cipher::State>() };
        let src_slice: &[u8] = if src_size == 0 {
            &[]
        } else if src.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_cipher_state_update: src is null"));
            return -1;
        } else {
            // SAFETY: caller upholds the size contract.
            unsafe { core::slice::from_raw_parts(src, src_size) }
        };
        // SAFETY: same.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst, dst_size) };
        match state.update(src_slice, dst_slice) {
            Ok(n) => isize::try_from(n).unwrap_or(-1),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                -1
            }
        }
    })
}

/// Finalize the cipher state and write any remaining bytes (including PKCS#7 padding for
/// CBC) to `dst`. Returns the number of bytes written (`>= 0`) on success or `-1` on error.
///
/// `dst` must have at least `cipher.block_size()` bytes of capacity.
///
/// # Safety
///
/// All pointers must be non-null and point to buffers of the documented sizes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_cipher_state_finalize(
    state: *mut core::ffi::c_void,
    dst: *mut u8,
    dst_size: usize,
) -> isize {
    with_panic_guard(|| {
        if state.is_null() || dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_cipher_state_finalize: null pointer"));
            return -1;
        }
        // SAFETY: caller guarantees the state pointer is alive.
        let state = unsafe { &mut *state.cast::<pgbr_crypto::cipher::State>() };
        // SAFETY: caller upholds the size + non-null contract.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst, dst_size) };
        match state.finalize(dst_slice) {
            Ok(n) => isize::try_from(n).unwrap_or(-1),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                -1
            }
        }
    })
}

// ---------- pgbr-crypto hash bridge (Phase 11) ----------

/// Allocate a fresh streaming hash state for `type_code` (0 = MD5, 1 = SHA1, 2 = SHA256).
///
/// Returns null on bad type or initialization failure; inspect the thread-local last error
/// for the cause.
///
/// The returned pointer must be released exactly once via [`pgbr_crypto_hash_state_free`].
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_crypto_hash_state_new(type_code: i32) -> *mut core::ffi::c_void {
    with_panic_guard(|| {
        let Some(ty) = pgbr_crypto::hash::HashType::from_code(type_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_crypto_hash_state_new: unknown type code {type_code}"),
            ));
            return core::ptr::null_mut();
        };
        match pgbr_crypto::hash::State::new(ty) {
            Ok(state) => Box::into_raw(Box::new(state)).cast::<core::ffi::c_void>(),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                core::ptr::null_mut()
            }
        }
    })
}

/// Drop a hash state previously returned by [`pgbr_crypto_hash_state_new`]. No-op on null.
///
/// # Safety
///
/// `state` must be a pointer previously returned by [`pgbr_crypto_hash_state_new`] that has
/// not yet been freed, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_hash_state_free(state: *mut core::ffi::c_void) {
    with_panic_guard(|| {
        if state.is_null() {
            return;
        }
        // SAFETY: caller upholds the unique-ownership invariant.
        let _ = unsafe { Box::from_raw(state.cast::<pgbr_crypto::hash::State>()) };
    });
}

/// Feed `size` bytes from `data` into the streaming state. Returns `0` on success, `-1` on
/// error (the thread-local last error is populated).
///
/// # Safety
///
/// - `state` must be a non-null pointer from [`pgbr_crypto_hash_state_new`].
/// - `data` must point to at least `size` readable bytes (or be null when `size == 0`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_hash_state_update(state: *mut core::ffi::c_void, data: *const u8, size: usize) -> i32 {
    with_panic_guard(|| {
        if state.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_hash_state_update: state is null"));
            return -1;
        }
        // SAFETY: caller guarantees the state pointer is alive and unaliased.
        let state = unsafe { &mut *state.cast::<pgbr_crypto::hash::State>() };
        let slice: &[u8] = if size == 0 {
            &[]
        } else if data.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_hash_state_update: data is null"));
            return -1;
        } else {
            // SAFETY: caller guarantees `data` is readable for `size` bytes.
            unsafe { core::slice::from_raw_parts(data, size) }
        };
        match state.update(slice) {
            Ok(()) => 0,
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                -1
            }
        }
    })
}

/// Finalize the streaming state and write up to `dst_size` digest bytes into `dst`. Returns
/// the number of bytes written on success or `-1` on error (thread-local last error set).
///
/// Idempotent: calling multiple times returns the same digest from the wrapper's cache, the
/// same way the legacy `cryptoHash()` getter cached its result.
///
/// # Safety
///
/// - `state` must be a non-null pointer from [`pgbr_crypto_hash_state_new`].
/// - `dst` must point to at least `dst_size` writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_hash_state_finalize_into(
    state: *mut core::ffi::c_void,
    dst: *mut u8,
    dst_size: usize,
) -> isize {
    with_panic_guard(|| {
        if state.is_null() || dst.is_null() {
            set_last_error(Error::new(
                ErrorType::Assert,
                "pgbr_crypto_hash_state_finalize_into: null argument",
            ));
            return -1;
        }
        // SAFETY: caller guarantees the state pointer is alive and unaliased.
        let state = unsafe { &mut *state.cast::<pgbr_crypto::hash::State>() };
        // SAFETY: caller guarantees `dst` is writable for `dst_size` bytes.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst, dst_size) };
        match state.finalize_into(dst_slice) {
            Ok(n) => isize::try_from(n).unwrap_or(-1),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                -1
            }
        }
    })
}

/// Single-shot hash.
///
/// Computes the digest of `msg_size` bytes at `msg` using the algorithm identified by
/// `type_code` and writes up to `dst_size` digest bytes into `dst`. Returns the number of
/// bytes written on success or `-1` on error (thread-local last error set).
///
/// # Safety
///
/// - `msg` must point to at least `msg_size` readable bytes (or be null when `msg_size == 0`).
/// - `dst` must point to at least `dst_size` writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_hash_one_into(
    type_code: i32,
    msg: *const u8,
    msg_size: usize,
    dst: *mut u8,
    dst_size: usize,
) -> isize {
    with_panic_guard(|| {
        let Some(ty) = pgbr_crypto::hash::HashType::from_code(type_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_crypto_hash_one_into: unknown type code {type_code}"),
            ));
            return -1;
        };
        if dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_hash_one_into: dst is null"));
            return -1;
        }
        let msg_slice: &[u8] = if msg_size == 0 {
            &[]
        } else if msg.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_hash_one_into: msg is null"));
            return -1;
        } else {
            // SAFETY: caller guarantees `msg` is readable for `msg_size` bytes.
            unsafe { core::slice::from_raw_parts(msg, msg_size) }
        };
        // SAFETY: caller guarantees `dst` is writable for `dst_size` bytes.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst, dst_size) };
        match pgbr_crypto::hash::one_shot(ty, msg_slice, dst_slice) {
            Ok(n) => isize::try_from(n).unwrap_or(-1),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                -1
            }
        }
    })
}

/// Single-shot HMAC. Returns the number of bytes written, or `-1` on error.
///
/// # Safety
///
/// - `key` must point to at least `key_size` readable bytes (or be null when `key_size == 0`).
/// - `msg` must point to at least `msg_size` readable bytes (or be null when `msg_size == 0`).
/// - `dst` must point to at least `dst_size` writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_crypto_hmac_one_into(
    type_code: i32,
    key: *const u8,
    key_size: usize,
    msg: *const u8,
    msg_size: usize,
    dst: *mut u8,
    dst_size: usize,
) -> isize {
    with_panic_guard(|| {
        let Some(ty) = pgbr_crypto::hash::HashType::from_code(type_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("pgbr_crypto_hmac_one_into: unknown type code {type_code}"),
            ));
            return -1;
        };
        if dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_hmac_one_into: dst is null"));
            return -1;
        }
        let key_slice: &[u8] = if key_size == 0 {
            &[]
        } else if key.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_hmac_one_into: key is null"));
            return -1;
        } else {
            // SAFETY: caller guarantees `key` is readable for `key_size` bytes.
            unsafe { core::slice::from_raw_parts(key, key_size) }
        };
        let msg_slice: &[u8] = if msg_size == 0 {
            &[]
        } else if msg.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_crypto_hmac_one_into: msg is null"));
            return -1;
        } else {
            // SAFETY: caller guarantees `msg` is readable for `msg_size` bytes.
            unsafe { core::slice::from_raw_parts(msg, msg_size) }
        };
        // SAFETY: caller guarantees `dst` is writable for `dst_size` bytes.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst, dst_size) };
        match pgbr_crypto::hash::hmac_one(ty, key_slice, msg_slice, dst_slice) {
            Ok(n) => isize::try_from(n).unwrap_or(-1),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Crypto, err.to_string()));
                -1
            }
        }
    })
}

/// Digest size in bytes for `type_code`, or `0` for an unknown code.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_crypto_hash_size(type_code: i32) -> usize {
    with_panic_guard(|| pgbr_crypto::hash::HashType::from_code(type_code).map_or(0, pgbr_crypto::hash::HashType::size))
}

// ---------- pgbr-regex bridge (Phase 9) ----------

/// Compile the NUL-terminated UTF-8 regular expression at `pattern` as a POSIX ERE.
///
/// Returns a non-null opaque handle on success that the caller must release via
/// [`pgbr_regex_free`]. Returns null on failure and sets the thread-local last error to
/// `FormatError` with the engine's diagnostic message — matching the legacy `regExpNew`'s
/// `THROW(FormatError, ...)` behaviour. The wrapper in `src/common/regExp.c` forwards that
/// message verbatim to the C exception machinery.
///
/// # Safety
///
/// `pattern` must be a non-null pointer to a NUL-terminated, readable byte sequence.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_regex_new(pattern: *const c_char) -> *mut core::ffi::c_void {
    with_panic_guard(|| {
        if pattern.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_regex_new: pattern is null"));
            return core::ptr::null_mut();
        }
        // SAFETY: caller guarantees `pattern` is NUL-terminated and readable.
        let bytes = unsafe { CStr::from_ptr(pattern) }.to_bytes();
        match pgbr_regex::Regex::new(bytes) {
            Ok(regex) => Box::into_raw(Box::new(regex)).cast::<core::ffi::c_void>(),
            Err(err) => {
                set_last_error(Error::new(ErrorType::Format, err.to_string()));
                core::ptr::null_mut()
            }
        }
    })
}

/// Drop a regex handle previously returned by [`pgbr_regex_new`]. No-op on null.
///
/// # Safety
///
/// `handle` must be a pointer previously returned by [`pgbr_regex_new`] that has not yet been
/// freed, or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_regex_free(handle: *mut core::ffi::c_void) {
    with_panic_guard(|| {
        if handle.is_null() {
            return;
        }
        // SAFETY: caller upholds the ownership invariant — the pointer came from
        // `pgbr_regex_new` and has not been freed.
        let _ = unsafe { Box::from_raw(handle.cast::<pgbr_regex::Regex>()) };
    });
}

/// Test whether `haystack` is matched by the regex at `handle`.
///
/// Returns `1` for a match, `0` for no match, `-1` on error (null arguments). On `-1` the
/// thread-local last error is set.
///
/// # Safety
///
/// - `handle` must be a non-null pointer from [`pgbr_regex_new`] that has not yet been freed.
/// - `haystack` must be a non-null pointer to a NUL-terminated, readable byte sequence.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_regex_match(handle: *const core::ffi::c_void, haystack: *const c_char) -> i32 {
    with_panic_guard(|| {
        if handle.is_null() || haystack.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_regex_match: null argument"));
            return -1;
        }
        // SAFETY: caller guarantees the handle is alive and unaliased.
        let regex = unsafe { &*handle.cast::<pgbr_regex::Regex>() };
        // SAFETY: caller guarantees `haystack` is NUL-terminated and readable.
        let bytes = unsafe { CStr::from_ptr(haystack) }.to_bytes();
        i32::from(regex.is_match(bytes))
    })
}

/// Locate the first match and write its byte offsets to `*start_out` / `*end_out`.
///
/// Returns `1` on match, `0` on no match, `-1` on error (null arguments). The output cells are
/// not written when the function returns `0` or `-1`.
///
/// Used by the build-time helper `regExpMatchPtr` / `regExpMatchStr` in
/// `src/build/common/regExp.c` to recover the same offsets the legacy code took from
/// `regmatch_t.rm_so` / `rm_eo`.
///
/// # Safety
///
/// - `handle` must be a non-null pointer from [`pgbr_regex_new`] that has not yet been freed.
/// - `haystack` must be a non-null pointer to a NUL-terminated, readable byte sequence.
/// - `start_out` and `end_out` must be non-null pointers to writable `usize` cells.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_regex_match_offsets(
    handle: *const core::ffi::c_void,
    haystack: *const c_char,
    start_out: *mut usize,
    end_out: *mut usize,
) -> i32 {
    with_panic_guard(|| {
        if handle.is_null() || haystack.is_null() || start_out.is_null() || end_out.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_regex_match_offsets: null argument"));
            return -1;
        }
        // SAFETY: caller guarantees the handle is alive and unaliased.
        let regex = unsafe { &*handle.cast::<pgbr_regex::Regex>() };
        // SAFETY: caller guarantees `haystack` is NUL-terminated and readable.
        let bytes = unsafe { CStr::from_ptr(haystack) }.to_bytes();
        match regex.find(bytes) {
            Some((start, end)) => {
                // SAFETY: caller guarantees `start_out` / `end_out` are writable.
                unsafe {
                    start_out.write(start);
                    end_out.write(end);
                }
                1
            }
            None => 0,
        }
    })
}

/// Length of the leading fixed-character prefix in `pattern`, or `0` when no usable prefix.
///
/// Excludes the leading `^` anchor. Mirrors `regExpPrefix` in `src/common/regExp.c` for the C
/// wrapper that materialises the result as a `String *`.
///
/// Returns `usize::MAX` if `pattern` is null and sets the thread-local last error.
///
/// # Safety
///
/// `pattern` must be a NUL-terminated, readable byte sequence (or null, which produces an
/// error return).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_regex_prefix_len(pattern: *const c_char) -> usize {
    with_panic_guard(|| {
        if pattern.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_regex_prefix_len: pattern is null"));
            return usize::MAX;
        }
        // SAFETY: caller guarantees `pattern` is NUL-terminated and readable.
        let bytes = unsafe { CStr::from_ptr(pattern) }.to_bytes();
        pgbr_regex::prefix_len(bytes)
    })
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    fn cstr(s: &str) -> CString {
        CString::new(s).unwrap()
    }

    #[test]
    fn version_is_non_empty_and_matches_cargo() {
        let ptr = pgbr_version();
        assert!(!ptr.is_null());
        // SAFETY: pgbr_version() returns a pointer to PGBR_FFI_VERSION, a 'static CStr.
        let result = unsafe { CStr::from_ptr(ptr) };
        let rust_str = result.to_str().expect("ffi version is utf-8");
        assert_eq!(rust_str, env!("CARGO_PKG_VERSION"));
        assert!(!rust_str.is_empty());
    }

    #[test]
    fn error_set_and_read_round_trip() {
        pgbr_last_error_clear();
        let msg = cstr("disk full while writing manifest");
        // SAFETY: msg owns a valid NUL-terminated UTF-8 buffer for the duration of the call.
        let rc = unsafe { pgbr_last_error_set(94, msg.as_ptr()) };
        assert_eq!(rc, 0);
        assert_eq!(pgbr_last_error_code(), 94);

        let msg_ptr = pgbr_last_error_msg();
        assert!(!msg_ptr.is_null());
        // SAFETY: msg_ptr is the cached CString in the thread-local slot; valid until next
        // mutation.
        let read = unsafe { CStr::from_ptr(msg_ptr) }.to_str().unwrap();
        assert_eq!(read, "disk full while writing manifest");

        let taken = pgbr_last_error_take_code();
        assert_eq!(taken, 94);
        assert_eq!(pgbr_last_error_code(), 0);
        assert!(pgbr_last_error_msg().is_null());
    }

    #[test]
    fn error_set_rejects_unknown_code_and_null_message() {
        pgbr_last_error_clear();
        let msg = cstr("ignored");

        // SAFETY: msg is a valid NUL-terminated buffer.
        let rc = unsafe { pgbr_last_error_set(7777, msg.as_ptr()) };
        assert_eq!(rc, -1);
        assert_eq!(pgbr_last_error_code(), 0);

        // SAFETY: explicit null pointer is allowed by the function's documented contract.
        let rc_null = unsafe { pgbr_last_error_set(94, std::ptr::null()) };
        assert_eq!(rc_null, -1);
        assert_eq!(pgbr_last_error_code(), 0);
    }

    #[test]
    fn panic_guard_does_not_auto_clear_so_readers_observe_state() {
        // The guard must not erase the slot on entry — otherwise reader shims would always return
        // 0 / null when called immediately after a writer.
        set_last_error(Error::new(ErrorType::Memory, "still here"));
        assert_eq!(pgbr_last_error_code(), 94);
        // pgbr_last_error_msg is also wrapped; if the guard auto-cleared, the pointer would be
        // null after this call.
        assert!(!pgbr_last_error_msg().is_null());
        pgbr_last_error_clear();
    }

    #[test]
    fn panic_guard_catches_panics_and_records_unknown_error() {
        let rc: i32 = with_panic_guard(|| panic!("boom"));
        assert_eq!(rc, -1);
        assert_eq!(pgbr_last_error_code(), 125);
        let msg_ptr = pgbr_last_error_msg();
        assert!(!msg_ptr.is_null());
        // SAFETY: pointer comes from the thread-local slot we just populated.
        let msg = unsafe { CStr::from_ptr(msg_ptr) }.to_str().unwrap();
        assert!(msg.contains("rust panic"));
        pgbr_last_error_clear();
    }

    static CALLBACK_HITS: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(0);
    static LAST_LEVEL: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(-99);

    extern "C" fn capture_callback(level: i32, _msg: *const c_char) {
        CALLBACK_HITS.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        LAST_LEVEL.store(level, std::sync::atomic::Ordering::SeqCst);
    }

    #[test]
    fn log_callback_round_trip() {
        CALLBACK_HITS.store(0, std::sync::atomic::Ordering::SeqCst);
        LAST_LEVEL.store(-99, std::sync::atomic::Ordering::SeqCst);

        // SAFETY: capture_callback is a static extern "C" function valid for the lifetime of the
        // process.
        unsafe { pgbr_log_set_callback(capture_callback) };
        pgbr_log(LogLevel::Warn as i32, "something happened");
        pgbr_log(LogLevel::Info as i32, "another");
        pgbr_log_clear_callback();
        pgbr_log(LogLevel::Error as i32, "should be dropped");

        assert_eq!(CALLBACK_HITS.load(std::sync::atomic::Ordering::SeqCst), 2);
        assert_eq!(LAST_LEVEL.load(std::sync::atomic::Ordering::SeqCst), LogLevel::Info as i32);
    }

    #[test]
    fn regex_new_matches_and_frees() {
        pgbr_last_error_clear();
        let pattern = cstr("^abc");
        // SAFETY: pattern is a valid NUL-terminated buffer.
        let handle = unsafe { pgbr_regex_new(pattern.as_ptr()) };
        assert!(!handle.is_null());
        assert_eq!(pgbr_last_error_code(), 0);

        let hay_match = cstr("abcdef");
        let hay_no = cstr("xyz");
        // SAFETY: handle is alive, haystack is NUL-terminated.
        assert_eq!(unsafe { pgbr_regex_match(handle, hay_match.as_ptr()) }, 1);
        // SAFETY: same.
        assert_eq!(unsafe { pgbr_regex_match(handle, hay_no.as_ptr()) }, 0);

        let mut start = 0usize;
        let mut end = 0usize;
        // SAFETY: handle alive, haystack NUL-terminated, output cells writable.
        let rc = unsafe { pgbr_regex_match_offsets(handle, hay_match.as_ptr(), &raw mut start, &raw mut end) };
        assert_eq!(rc, 1);
        assert_eq!((start, end), (0, 3));

        // SAFETY: handle came from pgbr_regex_new and is freed exactly once.
        unsafe { pgbr_regex_free(handle) };
    }

    #[test]
    fn regex_new_rejects_bad_pattern_and_sets_error() {
        pgbr_last_error_clear();
        let pattern = cstr("[[[");
        // SAFETY: pattern is a valid NUL-terminated buffer.
        let handle = unsafe { pgbr_regex_new(pattern.as_ptr()) };
        assert!(handle.is_null());
        assert_eq!(pgbr_last_error_code(), ErrorType::Format.code());

        let msg_ptr = pgbr_last_error_msg();
        assert!(!msg_ptr.is_null());
        // SAFETY: pointer comes from the thread-local slot just populated above.
        let msg = unsafe { CStr::from_ptr(msg_ptr) }.to_str().unwrap();
        assert!(msg.contains("regex parse error"), "expected diagnostic, got {msg:?}");
        pgbr_last_error_clear();
    }

    #[test]
    fn regex_match_offsets_no_match_leaves_outputs_unchanged() {
        let pattern = cstr("zzz");
        // SAFETY: pattern is NUL-terminated.
        let handle = unsafe { pgbr_regex_new(pattern.as_ptr()) };
        assert!(!handle.is_null());

        let hay = cstr("abcdef");
        let mut start = usize::MAX;
        let mut end = usize::MAX;
        // SAFETY: handle alive, haystack NUL-terminated, output cells writable.
        let rc = unsafe { pgbr_regex_match_offsets(handle, hay.as_ptr(), &raw mut start, &raw mut end) };
        assert_eq!(rc, 0);
        assert_eq!(
            (start, end),
            (usize::MAX, usize::MAX),
            "no-match must leave outputs untouched"
        );

        // SAFETY: handle came from pgbr_regex_new and is freed exactly once.
        unsafe { pgbr_regex_free(handle) };
    }

    #[test]
    fn regex_prefix_len_examples() {
        let cases: &[(&str, usize)] = &[
            ("", 0),
            ("abc", 0),
            ("^", 0),
            ("^.", 0),
            ("^ABC$", 3),
            ("^ABCDEF", 6),
            ("^ABC^", 0),
            ("^ABC[^DEF]", 3),
            ("^ABC\\^DEF", 3),
        ];
        for (pattern, expected) in cases {
            let c = cstr(pattern);
            // SAFETY: pattern is a valid NUL-terminated buffer.
            let len = unsafe { pgbr_regex_prefix_len(c.as_ptr()) };
            assert_eq!(len, *expected, "pattern {pattern:?}");
        }
    }

    #[test]
    fn regex_null_argument_returns_error() {
        pgbr_last_error_clear();
        // SAFETY: explicit null pointer is allowed by the function's documented contract.
        let h = unsafe { pgbr_regex_new(core::ptr::null()) };
        assert!(h.is_null());
        assert_ne!(pgbr_last_error_code(), 0);
        pgbr_last_error_clear();

        // SAFETY: same — null is the contract.
        let len = unsafe { pgbr_regex_prefix_len(core::ptr::null()) };
        assert_eq!(len, usize::MAX);
        assert_ne!(pgbr_last_error_code(), 0);
        pgbr_last_error_clear();
    }
}
