//! `pgbr-ffi` is the C ABI surface consumed by the legacy C build during the C->Rust migration.
//!
//! Each phase moves an additional `extern "C"` shim into this crate. The header `pgbr_ffi.h` is
//! regenerated by cbindgen from this crate at build time.
//!
//! Every C-callable function defined here goes through the [`with_panic_guard`] helper so panics
//! crossing the FFI boundary are caught and translated into a typed [`pgbr_error::ErrorType`]
//! value rather than aborting the process. C callers always observe well-defined return values
//! and can read the panic message via [`pgbr_last_error_msg`].

use core::ffi::{CStr, c_char};
use std::ffi::CString;
use std::sync::atomic::{AtomicPtr, Ordering};

use pgbr_encode::{self as encode, EncodingType};
use pgbr_error::{Error, ErrorType, clear_last_error, last_error_code, last_error_message, set_last_error};

/// Version string of the embedded Rust FFI shim, tracking `Cargo.toml`'s workspace version.
///
/// Baked into the static archive and returned to C as a NUL-terminated UTF-8 string.
// SAFETY: `CARGO_PKG_VERSION` is provided by Cargo and is guaranteed not to contain interior
// NULs; appending a single `\0` produces a well-formed C string.
const PGBR_FFI_VERSION: &CStr = unsafe { CStr::from_bytes_with_nul_unchecked(concat!(env!("CARGO_PKG_VERSION"), "\0").as_bytes()) };

/// Default value an `extern "C"` shim returns after a panic crosses its boundary.
///
/// Implemented for every type used as a return value from a [`with_panic_guard`]-wrapped FFI
/// values are deliberately chosen so a C caller observing them and inspecting
/// [`pgbr_last_error_code`] can distinguish a panic (`Unknown` = 125) from a clean operation.
pub trait FfiPanicReturn {
    /// Sentinel value returned when the wrapped Rust code panics.
    fn ffi_panic_return() -> Self;
}

impl FfiPanicReturn for () {
    fn ffi_panic_return() {}
}

impl FfiPanicReturn for i32 {
    fn ffi_panic_return() -> Self {
        -1
    }
}

impl FfiPanicReturn for usize {
    fn ffi_panic_return() -> Self {
        Self::MAX
    }
}

impl<T> FfiPanicReturn for *const T {
    fn ffi_panic_return() -> Self {
        core::ptr::null()
    }
}

impl<T> FfiPanicReturn for *mut T {
    fn ffi_panic_return() -> Self {
        core::ptr::null_mut()
    }
}

/// Run `body` while protecting the FFI boundary from a Rust panic.
///
/// If the body panics, the panic is recorded as the thread's last error
/// (category [`pgbr_error::ErrorType::Unknown`]) and the function returns the type's
/// [`FfiPanicReturn`] sentinel. Without this guard, a panic crossing the FFI boundary is
/// undefined behaviour.
///
/// The guard does **not** clear the thread-local error slot. Reader-style shims like
/// `pgbr_last_error_code` would otherwise erase the very value the C caller is trying to read.
/// A fallible Rust shim that wants to start from a clean slate should call
/// [`pgbr_error::clear_last_error`] inside the body before doing work.
fn with_panic_guard<R, F>(body: F) -> R
where
    R: FfiPanicReturn,
    F: FnOnce() -> R,
{
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(body)).unwrap_or_else(|_| {
        record_panic_as_last_error();
        R::ffi_panic_return()
    })
}

/// Internal helper used by [`with_panic_guard`] when `catch_unwind` traps a panic. Records a
/// typed `Unknown` error so the C caller can read the panic via [`pgbr_last_error_msg`].
fn record_panic_as_last_error() {
    set_last_error(Error::new(ErrorType::Unknown, "rust panic crossed FFI boundary"));
}

/// Returns a pointer to a static, NUL-terminated UTF-8 string identifying the Rust FFI shim
/// version. The pointer is valid for the lifetime of the process and must not be freed.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_version() -> *const c_char {
    with_panic_guard(|| PGBR_FFI_VERSION.as_ptr())
}

/// Numeric code of the calling thread's last error, or `0` if no error is set.
///
/// Mirrors the C `errorTypeCode` numbering. Reads the same thread-local slot populated by Rust
/// shims via `pgbr_error::set_last_error` and by the C-side helpers below.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_code() -> i32 {
    with_panic_guard(last_error_code)
}

/// Pointer to a NUL-terminated UTF-8 message of the calling thread's last error, or `null` if no
/// error is set.
///
/// The returned pointer is valid until the next call into `pgbr_last_error_*` on the same thread
/// (any of `pgbr_last_error_set`, `pgbr_last_error_clear`, `pgbr_last_error_take_code`). The
/// caller must not free it.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_msg() -> *const c_char {
    with_panic_guard(last_error_message)
}

/// Sets the calling thread's last error to the given typed `code` and `message_utf8` C string.
///
/// Returns `0` on success, `-1` if `code` is not part of the shared error table or
/// `message_utf8` is null or not valid UTF-8. On `-1`, the existing thread-local error is left
/// untouched.
///
/// # Safety
///
/// `message_utf8` must point to a NUL-terminated, valid UTF-8 byte sequence readable for the
/// duration of the call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_last_error_set(code: i32, message_utf8: *const c_char) -> i32 {
    with_panic_guard(|| {
        let Some(error_type) = ErrorType::from_code(code) else {
            return -1;
        };
        if message_utf8.is_null() {
            return -1;
        }
        // SAFETY: caller guarantees `message_utf8` is NUL-terminated and readable.
        let cstr = unsafe { CStr::from_ptr(message_utf8) };
        let Ok(message) = cstr.to_str() else {
            return -1;
        };
        set_last_error(Error::new(error_type, message));
        0
    })
}

/// Removes the calling thread's last error and returns its numeric code.
///
/// Returns `0` if no error was set. The associated message becomes invalid as soon as this
/// function returns.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_take_code() -> i32 {
    with_panic_guard(|| pgbr_error::take_last_error().map_or(0, |e| e.code()))
}

/// Clears the calling thread's last error.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_last_error_clear() {
    with_panic_guard(clear_last_error);
}

/// Logging callback registered by the C side to receive every Rust-originated log line.
///
/// The first argument is a numeric log level matching the C `LogLevel` enum (off=0, assert=1,
/// error=2, protocol=3, warn=4, info=5, detail=6, debug=7, trace=8). The second argument is a
/// pointer to a NUL-terminated UTF-8 message valid only during the call.
pub type PgbrLogCallback = unsafe extern "C" fn(level: i32, message_utf8: *const c_char);

static LOG_CALLBACK_RAW: AtomicPtr<()> = AtomicPtr::new(core::ptr::null_mut());

/// Registers a callback the Rust side invokes for every log line.
///
/// The callback is stored atomically and may be invoked from any thread. Replacing it is atomic
/// with respect to in-flight calls; in-flight calls always observe either the previous or the new
/// pointer, never a torn value. To stop receiving callbacks, use [`pgbr_log_clear_callback`].
///
/// # Safety
///
/// `callback` must be a valid `extern "C"` function pointer that remains live for as long as it
/// can be reached by the Rust side. The C side guarantees this by pointing to a static function.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_log_set_callback(callback: PgbrLogCallback) {
    with_panic_guard(|| {
        let raw: *mut () = callback as *mut ();
        LOG_CALLBACK_RAW.store(raw, Ordering::SeqCst);
    });
}

/// Removes any logging callback previously registered through [`pgbr_log_set_callback`]. After
/// this call, [`pgbr_log`] is a no-op until a new callback is installed.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_log_clear_callback() {
    with_panic_guard(|| {
        LOG_CALLBACK_RAW.store(core::ptr::null_mut(), Ordering::SeqCst);
    });
}

/// Forwards a log message to the registered callback, if any. Drops the message silently if no
/// callback has been set or if the message contains an interior NUL that cannot be removed.
///
/// Internal API used by other workspace crates; not exposed through cbindgen because it accepts
/// Rust types.
pub fn pgbr_log(level: i32, message: &str) {
    let raw = LOG_CALLBACK_RAW.load(Ordering::SeqCst);
    if raw.is_null() {
        return;
    }
    // SAFETY: the only writer of LOG_CALLBACK_RAW is `pgbr_log_set_callback`, which stores either
    // null or a `PgbrLogCallback` cast to `*mut ()`. We've checked for null above, so the pointer
    // is a valid function pointer when the callback was registered. Replacement is atomic.
    let callback: PgbrLogCallback = unsafe { core::mem::transmute(raw) };

    let cleaned: Vec<u8> = message.bytes().filter(|b| *b != 0).collect();
    let Ok(cstring) = CString::new(cleaned) else {
        return;
    };
    // SAFETY: the registered callback abides by extern "C" calling conventions and accepts a
    // pointer to a NUL-terminated UTF-8 buffer valid for the duration of the call.
    unsafe { callback(level, cstring.as_ptr()) };
}

/// Numeric mapping of the C `LogLevel` enum used by [`pgbr_log`] and [`PgbrLogCallback`]. The
/// values match the C side so a Rust producer and a C consumer can share a single integer.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LogLevel {
    /// Logging disabled.
    Off = 0,
    /// Programmer assertion violation; treated as fatal by the C side.
    Assert = 1,
    /// Recoverable error.
    Error = 2,
    /// Protocol-level diagnostic.
    Protocol = 3,
    /// Warning.
    Warn = 4,
    /// Informational message.
    Info = 5,
    /// Detailed informational message.
    Detail = 6,
    /// Debug-level diagnostic.
    Debug = 7,
    /// Trace-level diagnostic.
    Trace = 8,
}

// ---------- pgbr-encode bridge (Phase 6) ----------

/// Format a [`pgbr_encode::DecodeError`] using the legacy C error wording (`base64 size ...`,
/// `hex invalid character ...`) so the C wrappers in `src/common/encode.c` continue to throw
/// `FormatError` messages that match the existing test expectations.
fn format_decode_error(encoding: EncodingType, err: encode::DecodeError) -> String {
    let prefix = match encoding {
        EncodingType::Base64 | EncodingType::Base64Url => "base64",
        EncodingType::Hex => "hex",
    };
    match err {
        encode::DecodeError::InvalidLength { len, group } => {
            format!("{prefix} size {len} is not evenly divisible by {group}")
        }
        encode::DecodeError::InvalidCharacter { position } => {
            format!("{prefix} invalid character found at position {position}")
        }
        encode::DecodeError::PaddingMisplaced => {
            format!("{prefix} '=' character may only appear in last two positions")
        }
        encode::DecodeError::PaddingTrailing => {
            format!("{prefix} last character must be '=' if second to last is")
        }
        encode::DecodeError::Unsupported => format!("{prefix} decoding is not supported"),
    }
}

fn record_decode_error(encoding: EncodingType, err: encode::DecodeError) {
    set_last_error(Error::new(ErrorType::Format, format_decode_error(encoding, err)));
}

/// Encode `src_size` bytes at `src` into `dst` using the encoding selected by `encoding_code`
/// (0=Base64, 1=Base64Url, 2=Hex). Mirrors the legacy `encodeToStr` from `src/common/encode.h`.
///
/// The function writes `pgbr_encode::encoded_len(encoding, src_size) + 1` bytes (the encoded
/// form plus a trailing NUL).
///
/// # Safety
///
/// - `src` must point to at least `src_size` readable bytes (or be null when `src_size == 0`).
/// - `dst` must point to a writable buffer of at least `encoded_len(encoding, src_size) + 1`
///   bytes.
/// - `encoding_code` must be one of 0, 1, 2; any other value sets the thread-local error and
///   leaves `dst` untouched.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_encode_to_str(encoding_code: i32, src: *const u8, src_size: usize, dst: *mut c_char) {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return;
        };
        if dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_encode_to_str: dst is null"));
            return;
        }

        let dst_len = encode::encoded_len(encoding, src_size) + 1;
        // SAFETY: caller upholds the buffer size + non-null preconditions.
        let dst_slice = unsafe { core::slice::from_raw_parts_mut(dst.cast::<u8>(), dst_len) };
        let src_slice: &[u8] = if src_size == 0 {
            &[]
        } else {
            // SAFETY: caller guarantees `src` is readable for `src_size` bytes.
            unsafe { core::slice::from_raw_parts(src, src_size) }
        };

        encode::encode(encoding, src_slice, dst_slice);
    });
}

/// Returns `pgbr_encode::encoded_len(encoding, src_size)` — the size of the encoded form
/// excluding the trailing NUL. Mirrors the legacy `encodeToStrSize`.
///
/// Returns `usize::MAX` if `encoding_code` is unknown; the C wrapper translates that into a
/// `FormatError` throw via the thread-local last-error slot.
#[unsafe(no_mangle)]
pub extern "C" fn pgbr_encode_to_str_size(encoding_code: i32, src_size: usize) -> usize {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return usize::MAX;
        };
        encode::encoded_len(encoding, src_size)
    })
}

/// Decode the NUL-terminated UTF-8 string at `src` into `dst` using the encoding selected by
/// `encoding_code`. Mirrors the legacy `decodeToBin`.
///
/// Returns `0` on success, `-1` if validation failed; on `-1`, the thread-local last error is
/// populated with a `FormatError`-formatted message that the C wrapper re-throws.
///
/// # Safety
///
/// - `src` must be a valid NUL-terminated C string.
/// - `dst` must point to a writable buffer of at least `pgbr_decode_to_bin_size(encoding, src)`
///   bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_decode_to_bin(encoding_code: i32, src: *const c_char, dst: *mut u8) -> i32 {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return -1;
        };
        if src.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_decode_to_bin: src is null"));
            return -1;
        }

        // SAFETY: caller guarantees `src` is NUL-terminated.
        let cstr = unsafe { CStr::from_ptr(src) };
        let Ok(text) = cstr.to_str() else {
            set_last_error(Error::new(ErrorType::Format, "decode source is not valid utf-8"));
            return -1;
        };

        let needed = match encode::decoded_len(encoding, text) {
            Ok(n) => n,
            Err(err) => {
                record_decode_error(encoding, err);
                return -1;
            }
        };

        if needed > 0 && dst.is_null() {
            set_last_error(Error::new(ErrorType::Assert, "pgbr_decode_to_bin: dst is null"));
            return -1;
        }

        // SAFETY: caller upholds the dst sizing precondition.
        let dst_slice = if needed == 0 {
            &mut [][..]
        } else {
            unsafe { core::slice::from_raw_parts_mut(dst, needed) }
        };

        match encode::decode(encoding, text, dst_slice) {
            Ok(()) => 0,
            Err(err) => {
                record_decode_error(encoding, err);
                -1
            }
        }
    })
}

/// Computes the decoded byte size for the NUL-terminated string at `src`. Writes the result
/// through `out_size` and returns `0` on success, `-1` on validation failure.
///
/// On `-1`, `out_size` is left untouched and the thread-local last error carries the
/// `FormatError`-formatted reason.
///
/// # Safety
///
/// - `src` must be a valid NUL-terminated C string.
/// - `out_size` must point to a writable `usize` (8 bytes on 64-bit).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pgbr_decode_to_bin_size(encoding_code: i32, src: *const c_char, out_size: *mut usize) -> i32 {
    with_panic_guard(|| {
        let Some(encoding) = EncodingType::from_code(encoding_code) else {
            set_last_error(Error::new(
                ErrorType::Assert,
                format!("unknown EncodingType code {encoding_code}"),
            ));
            return -1;
        };
        if src.is_null() || out_size.is_null() {
            set_last_error(Error::new(
                ErrorType::Assert,
                "pgbr_decode_to_bin_size: src or out_size is null",
            ));
            return -1;
        }

        // SAFETY: caller guarantees `src` is NUL-terminated.
        let cstr = unsafe { CStr::from_ptr(src) };
        let Ok(text) = cstr.to_str() else {
            set_last_error(Error::new(ErrorType::Format, "decode source is not valid utf-8"));
            return -1;
        };

        match encode::decoded_len(encoding, text) {
            Ok(n) => {
                // SAFETY: caller guarantees `out_size` is writable.
                unsafe { out_size.write(n) };
                0
            }
            Err(err) => {
                record_decode_error(encoding, err);
                -1
            }
        }
    })
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    fn cstr(s: &str) -> CString {
        CString::new(s).unwrap()
    }

    #[test]
    fn version_is_non_empty_and_matches_cargo() {
        let ptr = pgbr_version();
        assert!(!ptr.is_null());
        // SAFETY: pgbr_version() returns a pointer to PGBR_FFI_VERSION, a 'static CStr.
        let result = unsafe { CStr::from_ptr(ptr) };
        let rust_str = result.to_str().expect("ffi version is utf-8");
        assert_eq!(rust_str, env!("CARGO_PKG_VERSION"));
        assert!(!rust_str.is_empty());
    }

    #[test]
    fn error_set_and_read_round_trip() {
        pgbr_last_error_clear();
        let msg = cstr("disk full while writing manifest");
        // SAFETY: msg owns a valid NUL-terminated UTF-8 buffer for the duration of the call.
        let rc = unsafe { pgbr_last_error_set(94, msg.as_ptr()) };
        assert_eq!(rc, 0);
        assert_eq!(pgbr_last_error_code(), 94);

        let msg_ptr = pgbr_last_error_msg();
        assert!(!msg_ptr.is_null());
        // SAFETY: msg_ptr is the cached CString in the thread-local slot; valid until next
        // mutation.
        let read = unsafe { CStr::from_ptr(msg_ptr) }.to_str().unwrap();
        assert_eq!(read, "disk full while writing manifest");

        let taken = pgbr_last_error_take_code();
        assert_eq!(taken, 94);
        assert_eq!(pgbr_last_error_code(), 0);
        assert!(pgbr_last_error_msg().is_null());
    }

    #[test]
    fn error_set_rejects_unknown_code_and_null_message() {
        pgbr_last_error_clear();
        let msg = cstr("ignored");

        // SAFETY: msg is a valid NUL-terminated buffer.
        let rc = unsafe { pgbr_last_error_set(7777, msg.as_ptr()) };
        assert_eq!(rc, -1);
        assert_eq!(pgbr_last_error_code(), 0);

        // SAFETY: explicit null pointer is allowed by the function's documented contract.
        let rc_null = unsafe { pgbr_last_error_set(94, std::ptr::null()) };
        assert_eq!(rc_null, -1);
        assert_eq!(pgbr_last_error_code(), 0);
    }

    #[test]
    fn panic_guard_does_not_auto_clear_so_readers_observe_state() {
        // The guard must not erase the slot on entry — otherwise reader shims would always return
        // 0 / null when called immediately after a writer.
        set_last_error(Error::new(ErrorType::Memory, "still here"));
        assert_eq!(pgbr_last_error_code(), 94);
        // pgbr_last_error_msg is also wrapped; if the guard auto-cleared, the pointer would be
        // null after this call.
        assert!(!pgbr_last_error_msg().is_null());
        pgbr_last_error_clear();
    }

    #[test]
    fn panic_guard_catches_panics_and_records_unknown_error() {
        let rc: i32 = with_panic_guard(|| panic!("boom"));
        assert_eq!(rc, -1);
        assert_eq!(pgbr_last_error_code(), 125);
        let msg_ptr = pgbr_last_error_msg();
        assert!(!msg_ptr.is_null());
        // SAFETY: pointer comes from the thread-local slot we just populated.
        let msg = unsafe { CStr::from_ptr(msg_ptr) }.to_str().unwrap();
        assert!(msg.contains("rust panic"));
        pgbr_last_error_clear();
    }

    static CALLBACK_HITS: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(0);
    static LAST_LEVEL: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(-99);

    extern "C" fn capture_callback(level: i32, _msg: *const c_char) {
        CALLBACK_HITS.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        LAST_LEVEL.store(level, std::sync::atomic::Ordering::SeqCst);
    }

    #[test]
    fn log_callback_round_trip() {
        CALLBACK_HITS.store(0, std::sync::atomic::Ordering::SeqCst);
        LAST_LEVEL.store(-99, std::sync::atomic::Ordering::SeqCst);

        // SAFETY: capture_callback is a static extern "C" function valid for the lifetime of the
        // process.
        unsafe { pgbr_log_set_callback(capture_callback) };
        pgbr_log(LogLevel::Warn as i32, "something happened");
        pgbr_log(LogLevel::Info as i32, "another");
        pgbr_log_clear_callback();
        pgbr_log(LogLevel::Error as i32, "should be dropped");

        assert_eq!(CALLBACK_HITS.load(std::sync::atomic::Ordering::SeqCst), 2);
        assert_eq!(LAST_LEVEL.load(std::sync::atomic::Ordering::SeqCst), LogLevel::Info as i32);
    }
}
