[package]
name = "pgbr-command"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]

[dependencies]
pgbr-build = { path = "../pgbr-build" }
pgbr-config = { path = "../pgbr-config" }
pgbr-error = { path = "../pgbr-error" }
pgbr-info = { path = "../pgbr-info" }
pgbr-io = { path = "../pgbr-io" }
pgbr-storage = { path = "../pgbr-storage" }
serde_json = "1"

[dev-dependencies]
serde_json = "1"
tempfile = "3"

[lints]
workspace = true
